---
title: "Patients clustering"
output: html_notebook
---

Input : normalized and filtered blood data
1) Consensus clustering
2) Association clusters with clinical data

### clean environment
```{r}
rm(list=ls())
```

### enter your path to folder
```{r}
path <- "~/Desktop/Code-PHD/Git/HIV_multiomics/"
```

### set directory
```{r setup}
    knitr::opts_knit$set(root.dir = normalizePath(path)) 
```

```{r}
name_ana <- "microbiome_project"
```

```{r}
library(xlsx)
library(gplots)
library(ComplexHeatmap)
library(circlize)
library(ConsensusClusterPlus)
library(limma)
library("colorspace")
```

```{r}
name_ana <- "microbiome_project"
```


```{r}
name_ana <- "microbiome_project"
```

```{r}
cluster <- read.csv("processing/cluster_SNF_3_omics_3_clusters.csv")
cluster$X <- NULL
names(cluster)[2] <- "X"
```

```{r}
clinical_data <- read.csv("processing/clinical_ordered_microbiome_project.csv")
```

```{r}
microbiome <- read.csv("processing/table_alpha_diversity.csv")
```

```{r}
clinical_data <- merge(clinical_data, microbiome, by = "X")
```


```{r}
clinical_data <- merge(cluster, clinical_data, by = "X")
```

## add depression data
```{r}
depression <- read.csv("data/Depression.csv")
depression <- select(depression, id, MDIsum)
names(depression)[1] <- "X"
```

```{r}
clinical_data <- merge(clinical_data, depression, by = "X", all.x = TRUE)
clinical_data$MDIsum <- as.numeric(clinical_data$MDIsum)
```

```{r}
clinical_data$MDIsum_2 <- NA
clinical_data$MDIsum_2 <- ifelse(clinical_data$MDIsum < 16, "No depression", clinical_data$MDIsum_2)
clinical_data$MDIsum_2 <- ifelse(clinical_data$MDIsum >= 16 & clinical_data$MDIsum < 22.5, "mild depression", clinical_data$MDIsum_2)
clinical_data$MDIsum_2 <- ifelse(clinical_data$MDIsum > 22.5 & clinical_data$MDIsum < 28.5, "moderate depression", clinical_data$MDIsum_2)
clinical_data$MDIsum_2 <- ifelse(clinical_data$MDIsum > 28.5, "severe depression", clinical_data$MDIsum_2)
```

```{r}
clinical_data$MDIsum_2 <- as.factor(clinical_data$MDIsum_2)
```

```{r}
table_2 <- clinical_data
rownames(table_2) <- table_2$X
table_2$X <- NULL
table_2$AGE <- as.numeric(table_2$AGE)
table_2$Combined_therapy <- NULL
table_2$Transm_mode <- NULL
```

```{r}
table_2$AGE <- as.numeric(table_2$AGE)
table_2$cluster <- as.factor(table_2$cluster)
table_2$METS <- as.factor(table_2$METS)
table_2$Ethnic <- as.factor(table_2$Ethnic)
table_2$Origin <- as.factor(table_2$Origin)
table_2$central_obesity <- as.factor(table_2$central_obesity)
table_2$diabetes <- as.factor(table_2$diabetes)
table_2$hypertension <- as.factor(table_2$hypertension)
table_2$GENDER <- as.factor(table_2$GENDER)
```

```{r}
table_2$Ethnic <- as.factor(ifelse(table_2$Ethnic != 1, 0, 1))
table_2$Origin <- as.factor(ifelse(table_2$Origin != 1, 0, 1))
```

```{r}
write.csv(table_2, "processing/summary_data_interest_COCOMO_microbiome.csv")
```


