---
title: "KW metabolomics"
output: html_notebook
---


### enter your path to folder
```{r}
path <- "/home/flomik/Desktop/Code-PHD/Git/HIV_multiomics"
```

### set directory
```{r setup}
    knitr::opts_knit$set(root.dir = normalizePath(path)) 
```

```{r}
library(gridExtra)
library(ggpubr)
library(xlsx)
library(gplots)
library(ComplexHeatmap)
library(circlize)
library(limma)
library("colorspace")
library(ggplot2)
library(dplyr)
library(scales)
```

```{r}
col <- c("#6b8150", "#2273C3","#EFC144","#868686")
col_border <- darken(col, 0.5)
```


```{r}
cluster <- read.csv("processing/cluster_SNF_3_omics_3_clusters.csv")
cluster$X <- NULL
names(cluster)[2] <- "X"
```

## load data

```{r}
data <- read.csv("/home/flomik/Desktop/Code-PHD/3_layers_integration/data/clp_um_new_data.csv", header = TRUE, check.names=FALSE)
names(data)[1] <- "X"
condition <- data$Group
#data$Group <- NULL
```

```{r}
data <- merge(cluster, data, by = "X", all.y = TRUE)
data$cluster <- ifelse(data$Group == "Ctrl", "Ctrl", data$cluster)
new_cluster <- data.frame(cluster = data$cluster, id = data$X)

data$X <- NULL
data$Group <- NULL
data <- data[!is.na(data$cluster),]
data$cluster <- factor(data$cluster, levels = c("Ctrl", 1, 2, 3))
```

## distribution-1
```{r}
hist(as.matrix(data[,-1]))

data[,-1] <- log2(data[,-1])
```


## boxplot
```{r}
list_box <- list()
x <- 1
for (i in 2:ncol(data)) {
  a <- ggplot(data, aes(x = cluster, y = data[,i], fill = cluster, color = cluster)) + 
    geom_boxplot(position=position_dodge(1), size = 0.5, alpha =0.8, outlier.shape = NA)+ theme(axis.title.x = element_text(size=16, face = "bold",color="black"),
          axis.title.y = element_text(size=16, face = "bold",color="black"),
          axis.text = element_text(color="black",size=16, face = "bold"),
          axis.text.x =element_text(color="black",size=16, face = "bold"),
          panel.border = element_blank(),
          axis.ticks.x = element_blank(),
          strip.text.x = element_text(size = 9,color="black"),
          legend.position="bottom",
          panel.background = element_rect(fill = "white", colour = "white", size = 0.5, linetype = "solid"),
          panel.grid.major = element_line(size = 0.5, linetype ='solid', colour = "grey"),
          panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "grey"),
          plot.title = element_text(hjust = 0.5, size = 20, face = "bold", vjust=2),
          legend.background=element_rect(fill = alpha("white", 0)))+ 
    labs(x="Cluster", y = paste0(names(data)[i], "")) + 
    geom_jitter(shape=16, size=2, color="black", position=position_jitter(0.02))+ scale_fill_manual(values=col)+ scale_color_manual(values=col_border)
  list_box[[x]] <- a
  x = x + 1
  ggsave(paste0("results/figures/boxplots/lipids_", colnames(data)[i], ".pdf"), height = 4, width = 3)
}
```

```{r}
pdf("results/figures/boxplots_lipids.pdf", height = 17, width = 10)
grid.arrange(list_box[[1]], list_box[[2]], list_box[[4]], list_box[[5]], list_box[[6]], list_box[[7]], list_box[[8]], list_box[[9]], list_box[[10]], list_box[[11]], list_box[[12]], list_box[[13]], nrow = 4)
dev.off()
```
