---
title: "Preprocessing input files"
output: html_notebook
---




### enter your path to folder
```{r}
path <- "/home/flomik/Desktop/Code-PHD/Git/HIV_multiomics"
```

### set directory
```{r setup}
    knitr::opts_knit$set(root.dir = normalizePath(path)) 
```

```{r}
library(xlsx)
```

## Lipidomics
```{r}
#data_lip <- read.xlsx("/home/flomik/Desktop/Code-PHD/Git/HIV_multiomics/data/Original_Scale_Data_CLP.xlsx", 1)
data_lip <- read.csv("data/clp_lipidomics_data.csv")

lip_sup_pathways <- data_lip[,c(1, 2)]
write.csv(lip_sup_pathways, "processing/lipids_superpathways.csv", row.names = FALSE, quote = FALSE)
```

## Metabolomics
```{r}
#data_met <- read.xlsx("/home/flomik/Desktop/Code-PHD/Git/HIV_multiomics/data/Supplementary Data 1.xlsx", 1)
data_met <- read.csv("data/cocomo_norm_data_filt.csv")

met_sup_pathways <- data_met[,c(1, 2)]
write.csv(met_sup_pathways, "processing/biochemical_super_path.csv", row.names = FALSE, quote = FALSE)

met_sup_sub_pathways <- data_met[,c(1, 2, 3)]
write.csv(met_sup_pathways, "processing/metabolites_pathways.csv", row.names = FALSE, quote = FALSE)
```

## Microbiome
### select rarefied files for genus, family and phylum
```{r}
data_genus <- read.xlsx("data/COCOMO-request.SHH.withfamilyandphylum.xlsx", 2)
write.csv(data_genus, "data/microbiome_COCOMO_genus.csv")

data_family <- read.xlsx("data/COCOMO-request.SHH.withfamilyandphylum.xlsx", 4)
write.csv(data_family, "data/microbiome_COCOMO_family.csv")

data_phylum <- read.xlsx("data/COCOMO-request.SHH.withfamilyandphylum.xlsx", 6)
write.csv(data_phylum, "data/microbiome_COCOMO_phylum.csv")
```
## Clinical
```{r}
a <- read.csv("/home/flomik/Desktop/Code-PHD/3_layers_integration/processing/table_clinical_data.csv")
```




"data/clinical_data_of_interest_microbiome_project.csv"
"clinical_ordered_microbiome_project.csv"
table_clinical_data.csv
